-- 코드를 입력하세요
SELECT
    DATE_FORMAT(ONS.SALES_DATE, '%Y-%m-%d'),
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM
    ONLINE_SALE AS ONS
WHERE
    EXTRACT(YEAR_MONTH FROM ONS.SALES_DATE) = '202203'
UNION ALL
SELECT
    DATE_FORMAT(OFFS.SALES_DATE, '%Y-%m-%d'),
    PRODUCT_ID,
    NULL AS USER_ID,
    SALES_AMOUNT    
FROM
    OFFLINE_SALE AS OFFS
WHERE
    EXTRACT(YEAR_MONTH FROM OFFS.SALES_DATE) = '202203'
ORDER BY
    1 ASC,
    PRODUCT_ID ASC,
    USER_ID ASC