-- 코드를 입력하세요
SELECT
    AIS.ANIMAL_ID,
    AIS.ANIMAL_TYPE,
    AIS.NAME
FROM
    ANIMAL_INS AS AIS
    INNER JOIN ANIMAL_OUTS AS AOS
    ON AIS.ANIMAL_ID = AOS.ANIMAL_ID
WHERE
    AIS.SEX_UPON_INTAKE LIKE 'Intact%'
    AND AIS.SEX_UPON_INTAKE != AOS.SEX_UPON_OUTCOME
ORDER BY
    AIS.ANIMAL_ID ASC;