-- 코드를 입력하세요

SELECT
    CR.HISTORY_ID,
    CASE
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90
    THEN ROUND((CC.DAILY_FEE * 85/100) * (DATEDIFF(END_DATE, START_DATE) + 1),0)
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30
    THEN ROUND((CC.DAILY_FEE * 92/100) * (DATEDIFF(END_DATE, START_DATE) + 1),0)
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7
    THEN ROUND((CC.DAILY_FEE * 95/100) * (DATEDIFF(END_DATE, START_DATE) + 1),0)
    ELSE (CC.DAILY_FEE) * (DATEDIFF(END_DATE, START_DATE) + 1)
    END AS FEE
    
FROM
    CAR_RENTAL_COMPANY_CAR AS CC
        INNER JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CR ON CC.CAR_ID = CR.CAR_ID
WHERE
    CC.CAR_TYPE='트럭'
ORDER BY
    2 DESC,
    1 DESC